### ISSUE TITLE
Small list error

### ISSUE THREAD

**Issue by emilyxxie** [spruce/ep_small_list#4]
Hey, looks like ep_small_list has an issue. The last item on the small list is a bug. It's comprised of the already-listed pads separated by commas. If you click on it, you get an error message that says "such a padname is forbidden"

![image](https://cloud.githubusercontent.com/assets/5360525/7435766/a032682a-f014-11e4-83d3-dd67c9a8037c.png)

**Comment by spruce** [comment]
That is really strange. I think I had the problem before to. Even the original Plugin uses this. I will write an update to this plugin to detect commas in the name and then simply filter them out. https://github.com/JohnMcLear/ep_list_pads/blob/master/index.js#L21

**Comment by emilyxxie** [comment]
If it helps at all, for some reason, this rogue bullet point disappears whenever we restart etherpad. I haven't been able to recreate the issue today since restarting, but I'll see if I can track it down and give fixing it a shot too.

**Comment by spruce** [comment]
Can you maybe open an issue on the etherpad repo? also giving this picture? I will try and write a workaround which should mitigate having commas in names which shouldn't even be possible

**Comment by spruce** [comment]
Can You check whether v0.0.5 fixes you problem?

**Comment by robfantini** [comment]
Hello,    using v0.0.5 and have the same issue..    PS:  thank you for this plugin!

**Comment by Sergio3** [comment]
Same bug here, with v.0.0.5 and latest etherpad. Thank you anyway for all your fantastic work!!!!

**Comment by spruce** [comment]
Ok. So I will create a new fix. There I will simply check whether the padID contains a comma and then skip it.

**Comment by xdaniel91536** [comment]
This problem exists when using DirtyDB.. Changing to an MySQL Database fixed the problem for me!

For the Dev: Reproducing the Bug works by reloading the index page after restarting the Server and creating a new pad.

Contact me via Email: xaribusiness@gmail.com

**Comment by spruce** [comment]
Thanks for reporting.

That's nice to know. If i've got some time soon. I gonna look more into it.

**Comment by spruce** [comment]
I think the problem doesn't lie in this plugin but more in the Etherpad API which wrongly returns the all the pads comma seperated. If one would be willing to create a issue there that would, I think, be leading to a solution quicker.

**Comment by spruce** [comment]
As of d6fa935 it should actually be fixed. I just released a new version. Can you check whether it works with v0.1.0?

**Comment by Wikinaut** [comment]
I have the same problem, running apparently the lastest version of  ep_small_list, and noticed the following:

* the spooky pad name (all padnames, comma-separated) appears always after I deleted a pad using the https://www.npmjs.com/package/ep_adminpads plugin.

**Comment by spruce** [comment]
@Wikinaut what OS are you using? Also DirtyDB? I still strongly believe it isn't caused by ep_small_list

**Comment by Wikinaut** [comment]
* debian 8 (Jessie) fully patched
* MySQL

**Comment by spruce** [comment]
Does the problem remain after restart etherpad?

**Comment by Wikinaut** [comment]
I can confirm that a stop/start-cycle **clears** the sppoky entry. (I just checked it: I _had_ the delete_empty_pad plugin installed before, but removed that for test)

**Comment by Wikinaut** [comment]
@spruce some more news, here how to reproduce.

Prerequisite: https://www.npmjs.com/package/ep_adminpads

* create a test pad "test"
* add some characters on that pad
* navigate to /admin
* click "Manage pads" (this entry is added by ep_adminpads)
* delete the test pad "test"
* go back to the Etherpad start page

ep_small_list now shows the spooky entry (all file names, the "test" pad is not longer listed).

I hope this helps to find, and finally to fix, the bug.

**Comment by spruce** [comment]
Ok, I gonna look into it some more. With a reproduction it should be easier to find the bug. Thanks for working that out.

**Comment by Wikinaut** [comment]
Perhaps you can help: /admin plugin page shows "...fetching" in the lower part, what's wrong with the etherpad main module ?

**Comment by Wikinaut** [comment]
Thanks, I can confirm that your fix appears to solve the problem, I used a manual deinstallation via /admin/plugins and manual installation `sudo -u etherpad npm install ep_small_list` because of current issue https://github.com/ether/etherpad-lite/issues/3090 .
