### ISSUE TITLE
ep_small_list is not working with current Etherpad

### ISSUE THREAD

**Issue by Wikinaut** [spruce/ep_small_list#5]
ep_small_list does not work with
* https://github.com/ether/etherpad-lite/commit/ba9b9c99314372dfe2184d96a5d01f4fc2efc824

**Comment by spruce** [comment]
@Wikinaut can you explain what is not working?

**Comment by Wikinaut** [comment]
In the current Etherpad, the Plugin is not listing pads on the index page.

**Comment by spruce** [comment]
The API I was using changed. So i updated the plugin. Now it should work again. If you got another problem please open a new issue.

**Comment by Wikinaut** [comment]
Something is still broken:

```
sudo -u etherpad npm install ep_small_list

npm WARN enoent ENOENT: no such file or directory, open '/srv/etherpad/package.json'
npm WARN etherpad No description
npm WARN etherpad No repository field.
npm WARN etherpad No README data
npm WARN etherpad No license field.

npm ERR! path /srv/etherpad/node_modules/.staging/ep_etherpad-lite-72d6b1d4/node_modules/@babel/code-frame
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/srv/etherpad/node_modules/.staging/ep_etherpad-lite-72d6b1d4/node_modules/@babel/code-frame' -> '/srv/etherpad/node_modules/.staging/@babel/code-frame-f7e32e9f'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/etherpad/.npm/_logs/2019-05-14T09_16_02_307Z-debug.log
```

**Comment by Wikinaut** [comment]
pls. can you assist?

**Comment by spruce** [comment]
I get the same warning about the package.json not existing. 
But I can't reproduce the next error, sorry.

**Comment by Wikinaut** [comment]
try updatePlugins.sh:

```
/srv/etherpad/bin$ sudo -u etherpad ./updatePlugins.sh 
Plugins require update, doing this now...
Updating async
bcrypt
ep_small_list
npm WARN enoent ENOENT: no such file or directory, open '/srv/etherpad/package.json'
npm WARN etherpad No description
npm WARN etherpad No repository field.
npm WARN etherpad No README data
npm WARN etherpad No license field.

npm ERR! path /srv/etherpad/node_modules/.staging/ep_etherpad-lite-72d6b1d4/node_modules/@babel/code-frame
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/srv/etherpad/node_modules/.staging/ep_etherpad-lite-72d6b1d4/node_modules/@babel/code-frame' -> '/srv/etherpad/node_modules/.staging/@babel/code-frame-f7e32e9f'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/etherpad/.npm/_logs/2019-05-14T12_19_46_413Z-debug.log
```

**Comment by Wikinaut** [comment]
And when I try to uninstall the previous version via the /admin page:

![grafik](https://user-images.githubusercontent.com/1151915/57697513-b4d91700-7653-11e9-89f4-2abd76cd75d2.png)

**Comment by Wikinaut** [comment]
And the list of available plugins still shows the old version number:

![grafik](https://user-images.githubusercontent.com/1151915/57698666-6b3dfb80-7656-11e9-9672-8b8dfcac0d73.png)

**Comment by spruce** [comment]
It looks to me, like your installation is not complete. I still cannot reproduce the issue.

**Comment by degers** [comment]
Etherpad 1.6 offers Plugin Version 0.2.0 in Backend, which doesn't work, can confirm

**Comment by spruce** [comment]
Which node version are you running? 
My etherpad git hash is https://github.com/ether/etherpad-lite/commit/04a45fbe46a71bc294c6e9ad355e96fcb10f9685
When installing the version 0.2.0 from the backend it will still install the newest version (0.3.0) of this plugin.
So for me it works as it is intended.
